"""empty message

Revision ID: 0356d1de9755
Revises: 063d317207ac
Create Date: 2026-03-08 16:42:21.122379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0356d1de9755'
down_revision = '063d317207ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_projects_department_id'), ['department_id'], unique=False)
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_projects_department_id'))
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
