"""empty message

Revision ID: 063d317207ac
Revises: 1b4ab9aecf6a
Create Date: 2026-03-08 16:12:18.839146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063d317207ac'
down_revision = '1b4ab9aecf6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('head_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['head_id'])
        batch_op.create_foreign_key(None, 'users', ['head_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_department_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_department_id_fkey'), 'departments', ['department_id'], ['id'])

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('head_id')

    # ### end Alembic commands ###
