"""empty message

Revision ID: 1b4ab9aecf6a
Revises: 50bd11cf63d3
Create Date: 2026-03-04 20:38:23.933584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b4ab9aecf6a'
down_revision = '50bd11cf63d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('to_do', 'in_progress', 'in_review', 'done', name='status'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'head', 'staff', 'guest', name='rolename'),
               type_=sa.Enum('admin', 'head', 'staff', 'guest', name='role_name'),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('users_department_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_department_id_fkey'), 'departments', ['department_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'head', 'staff', 'guest', name='role_name'),
               type_=postgresql.ENUM('admin', 'head', 'staff', 'guest', name='rolename'),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('to_do', 'in_progress', 'in_review', 'done', name='status'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
