"""empty message

Revision ID: 1b4ab9aecf6a
Revises: 50bd11cf63d3
Create Date: 2026-03-04 20:38:23.933584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b4ab9aecf6a'
down_revision = '50bd11cf63d3'
branch_labels = None
depends_on = None

status_enum = sa.Enum(
    "to_do",
    "in_progress",
    "in_review",
    "done",
    name="status"
)

role_name_enum = sa.Enum(
    "admin",
    "head",
    "staff",
    "guest",
    name="rolename"
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=50),
            type_=status_enum,
            existing_nullable=False,
            postgresql_using="status::status"
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.drop_constraint(batch_op.f(
            'users_department_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(
            None, 'departments', ['department_id'], ['id'])

        batch_op.drop_constraint(batch_op.f(
            'users_department_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(
            None, 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=status_enum,
            type_=sa.VARCHAR(length=50),
            existing_nullable=False,
            postgresql_using="status::text"
        )

    status_enum.drop(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
                              existing_type=sa.Enum(
                                  'to_do', 'in_progress', 'in_review', 'done', name='status'),
                              type_=sa.VARCHAR(length=50),
                              existing_nullable=False)

    # ### end Alembic commands ###
